from functools import reduce

from src.challenges.sectional.domain_logic.section_snippet_subtotal_type import (
    StudentSnippet1, merge_snippet_lists_1,
)


class test_full_set:
    students = [
        StudentSnippet1(
            FirstLineIndex=0,
            LastLineIndex=0,
            StudentId=1,
            StudentName='John1',
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=1,
            LastLineIndex=1,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate='2017-02-01',
            LastTrimesterDate='2017-02-01',
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=2,
            LastLineIndex=2,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 1],
            WeightedGradeTotal=[0, 0, 0, 1]),
        StudentSnippet1(
            FirstLineIndex=3,
            LastLineIndex=3,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[4, 0, 0, 0],
            WeightedGradeTotal=[4, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=4,
            LastLineIndex=4,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 3, 0],
            WeightedGradeTotal=[0, 0, 15, 0]),
        StudentSnippet1(
            FirstLineIndex=5,
            LastLineIndex=5,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 2],
            WeightedGradeTotal=[0, 0, 0, 8]),
        StudentSnippet1(
            FirstLineIndex=6,
            LastLineIndex=6,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=3,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=7,
            LastLineIndex=7,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate='2017-03-01',
            LastTrimesterDate='2017-03-01',
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=8,
            LastLineIndex=8,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 1, 0, 0],
            WeightedGradeTotal=[0, 5, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=9,
            LastLineIndex=9,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 1, 0],
            WeightedGradeTotal=[0, 0, 2, 0]),
        StudentSnippet1(
            FirstLineIndex=10,
            LastLineIndex=10,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 3, 0],
            WeightedGradeTotal=[0, 0, 6, 0]),
        StudentSnippet1(
            FirstLineIndex=11,
            LastLineIndex=11,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[4, 0, 0, 0],
            WeightedGradeTotal=[16, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=12,
            LastLineIndex=12,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=1,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=13,
            LastLineIndex=13,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate='2017-04-01',
            LastTrimesterDate='2017-04-01',
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=14,
            LastLineIndex=14,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 3, 0],
            WeightedGradeTotal=[0, 0, 15, 0]),
        StudentSnippet1(
            FirstLineIndex=15,
            LastLineIndex=15,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[1, 0, 0, 0],
            WeightedGradeTotal=[2, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=16,
            LastLineIndex=16,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[2, 0, 0, 0],
            WeightedGradeTotal=[10, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=17,
            LastLineIndex=17,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[3, 0, 0, 0],
            WeightedGradeTotal=[15, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=18,
            LastLineIndex=18,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=1,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=19,
            LastLineIndex=19,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate='2017-05-01',
            LastTrimesterDate='2017-05-01',
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=20,
            LastLineIndex=20,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 1],
            WeightedGradeTotal=[0, 0, 0, 4]),
        StudentSnippet1(
            FirstLineIndex=21,
            LastLineIndex=21,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 1, 0, 0],
            WeightedGradeTotal=[0, 5, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=22,
            LastLineIndex=22,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 3],
            WeightedGradeTotal=[0, 0, 0, 15]),
        StudentSnippet1(
            FirstLineIndex=23,
            LastLineIndex=23,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 2, 0],
            WeightedGradeTotal=[0, 0, 4, 0]),
        StudentSnippet1(
            FirstLineIndex=24,
            LastLineIndex=24,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=1,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=25,
            LastLineIndex=25,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate='2017-06-01',
            LastTrimesterDate='2017-06-01',
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=26,
            LastLineIndex=26,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 2, 0],
            WeightedGradeTotal=[0, 0, 4, 0]),
        StudentSnippet1(
            FirstLineIndex=27,
            LastLineIndex=27,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 2],
            WeightedGradeTotal=[0, 0, 0, 6]),
        StudentSnippet1(
            FirstLineIndex=28,
            LastLineIndex=28,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 4],
            WeightedGradeTotal=[0, 0, 0, 12]),
        StudentSnippet1(
            FirstLineIndex=29,
            LastLineIndex=29,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 1],
            WeightedGradeTotal=[0, 0, 0, 3]),
        StudentSnippet1(
            FirstLineIndex=30,
            LastLineIndex=30,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=1,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=31,
            LastLineIndex=31,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate='2017-07-01',
            LastTrimesterDate='2017-07-01',
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=32,
            LastLineIndex=32,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 1],
            WeightedGradeTotal=[0, 0, 0, 3]),
        StudentSnippet1(
            FirstLineIndex=33,
            LastLineIndex=33,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 2],
            WeightedGradeTotal=[0, 0, 0, 10]),
        StudentSnippet1(
            FirstLineIndex=34,
            LastLineIndex=34,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[2, 0, 0, 0],
            WeightedGradeTotal=[2, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=35,
            LastLineIndex=35,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 2, 0, 0],
            WeightedGradeTotal=[0, 8, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=36,
            LastLineIndex=36,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=1,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=37,
            LastLineIndex=37,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate='2017-08-01',
            LastTrimesterDate='2017-08-01',
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=38,
            LastLineIndex=38,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 3],
            WeightedGradeTotal=[0, 0, 0, 6]),
        StudentSnippet1(
            FirstLineIndex=39,
            LastLineIndex=39,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[4, 0, 0, 0],
            WeightedGradeTotal=[16, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=40,
            LastLineIndex=40,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 3, 0, 0],
            WeightedGradeTotal=[0, 15, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=41,
            LastLineIndex=41,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 3, 0],
            WeightedGradeTotal=[0, 0, 6, 0]),
        StudentSnippet1(
            FirstLineIndex=42,
            LastLineIndex=42,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=1,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=43,
            LastLineIndex=43,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate='2017-09-01',
            LastTrimesterDate='2017-09-01',
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=44,
            LastLineIndex=44,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 3, 0],
            WeightedGradeTotal=[0, 0, 6, 0]),
        StudentSnippet1(
            FirstLineIndex=45,
            LastLineIndex=45,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 0, 4],
            WeightedGradeTotal=[0, 0, 0, 12]),
        StudentSnippet1(
            FirstLineIndex=46,
            LastLineIndex=46,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 0, 2, 0],
            WeightedGradeTotal=[0, 0, 2, 0]),
        StudentSnippet1(
            FirstLineIndex=47,
            LastLineIndex=47,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=None,
            Credits=[0, 4, 0, 0],
            WeightedGradeTotal=[0, 20, 0, 0]),
        StudentSnippet1(
            FirstLineIndex=48,
            LastLineIndex=48,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=1,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0])
    ]

    def test_start(self):
        r = merge_snippet_lists_1([self.students[0]], [self.students[1]])
        assert r == [StudentSnippet1(
            FirstLineIndex=0,
            LastLineIndex=1,
            StudentId=1,
            StudentName='John1',
            FirstTrimesterDate='2017-02-01',
            LastTrimesterDate='2017-02-01',
            LastMajor=None,
            Credits=[0, 0, 0, 0],
            WeightedGradeTotal=[0, 0, 0, 0])]

    def test_end(self):
        r = merge_snippet_lists_1([self.students[-2]], [self.students[-1]])
        assert r == [StudentSnippet1(
            FirstLineIndex=47,
            LastLineIndex=48,
            StudentId=None,
            StudentName=None,
            FirstTrimesterDate=None,
            LastTrimesterDate=None,
            LastMajor=1,
            Credits=[0, 4, 0, 0],
            WeightedGradeTotal=[0, 20, 0, 0])]

    def test_full(self):
        r = reduce(merge_snippet_lists_1, map(lambda x: [x], self.students))
        assert r == [StudentSnippet1(
            FirstLineIndex=0,
            LastLineIndex=48,
            StudentId=1,
            StudentName='John1',
            FirstTrimesterDate='2017-02-01',
            LastTrimesterDate='2017-09-01',
            LastMajor=1,
            Credits=[20, 11, 22, 24],
            WeightedGradeTotal=[65, 53, 60, 80])]
