from src.challenges.six_field_test_data.six_test_data_for_dask import ChallengeMethodPythonDaskRegistration

CONDITIONAL_STRATEGIES_USING_DASK_REGISTRY: list[ChallengeMethodPythonDaskRegistration] = [
]
